In [1]:
%%capture
!pip install transformers datasets

In [3]:
from datasets import load_dataset
squad=load_dataset("squad")

In [4]:
squad

DatasetDict({
    train: Dataset({
        features: ['id', 'title', 'context', 'question', 'answers'],
        num_rows: 87599
    })
    validation: Dataset({
        features: ['id', 'title', 'context', 'question', 'answers'],
        num_rows: 10570
    })
})

BERT has many Classes each represent a different model for specific use cases like Question Answering, Text Classification, Summarization

In [6]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModelForQuestionAnswering.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


TFAutoModel from Transformers gives us the low level authority, from which we can add more layers.

In [7]:
model

BertForQuestionAnswering(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, 

In [9]:
question="What are the benifits of eating a banana"

In [10]:
context="Bananas offer a versatile and delicious way to support overall health and well-being. Benefits include supporting digestive health, improving heart health, and providing energy. They're also a natural source of sweetness, which can satisfy cravings without the added sugar and additives found in processed sweet treats."

In [27]:
inputs=tokenizer(question,context, return_tensors="pt")
inputs

{'input_ids': tensor([[  101,  2054,  2024,  1996,  3841, 10128, 12762,  1997,  5983,  1037,
         15212,   102, 26191,  3749,  1037, 22979,  1998, 12090,  2126,  2000,
          2490,  3452,  2740,  1998,  2092,  1011,  2108,  1012,  6666,  2421,
          4637, 17886,  3512,  2740,  1010,  9229,  2540,  2740,  1010,  1998,
          4346,  2943,  1012,  2027,  1005,  2128,  2036,  1037,  3019,  3120,
          1997, 23210,  1010,  2029,  2064, 13225, 26369,  2015,  2302,  1996,
          2794,  5699,  1998, 29167,  2015,  2179,  1999, 13995,  4086, 18452,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [28]:
input_ids=inputs["input_ids"]
attention_mask=inputs["attention_mask"]
input_ids,attention_mask

(tensor([[  101,  2054,  2024,  1996,  3841, 10128, 12762,  1997,  5983,  1037,
          15212,   102, 26191,  3749,  1037, 22979,  1998, 12090,  2126,  2000,
           2490,  3452,  2740,  1998,  2092,  1011,  2108,  1012,  6666,  2421,
           4637, 17886,  3512,  2740,  1010,  9229,  2540,  2740,  1010,  1998,
           4346,  2943,  1012,  2027,  1005,  2128,  2036,  1037,  3019,  3120,
           1997, 23210,  1010,  2029,  2064, 13225, 26369,  2015,  2302,  1996,
           2794,  5699,  1998, 29167,  2015,  2179,  1999, 13995,  4086, 18452,
           1012,   102]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [29]:
import torch
with torch.no_grad():
  outputs=model(input_ids=input_ids, attention_mask=attention_mask)

outputs

QuestionAnsweringModelOutput(loss=None, start_logits=tensor([[-0.7289,  0.0216, -0.0084, -0.3371, -0.0077,  0.0030,  0.0014, -0.3549,
         -0.2049, -0.2091,  0.2694,  0.1048, -0.1884, -0.0416, -0.4374, -0.3508,
         -0.4671, -0.2463, -0.0794, -0.5153,  0.0374, -0.0657,  0.1103, -0.1523,
         -0.1970, -0.2279, -0.0684,  0.1575, -0.1281, -0.3709, -0.0592, -0.0275,
         -0.2474,  0.1341, -0.1313, -0.3445, -0.4873,  0.2079,  0.0503, -0.4922,
         -0.4787, -0.2708,  0.1646, -0.5863,  0.0662, -0.1516, -0.4108, -0.2930,
         -0.1739, -0.1531, -0.4577, -0.1034,  0.0865, -0.3849, -0.4483, -0.2298,
         -0.1915, -0.5178, -0.3446, -0.4866, -0.5707, -0.2190, -0.3965, -0.3881,
         -0.3193, -0.0837, -0.5666, -0.3479,  0.1039, -0.1174,  0.1737,  0.1091]]), end_logits=tensor([[-0.1349,  0.1796,  0.2238,  0.1317, -0.0844, -0.5774, -0.0758,  0.5350,
          0.4935,  0.1708,  0.0574, -0.0029, -0.4027,  0.2622, -0.0501,  0.1308,
         -0.1449, -0.1009,  0.3041, -0.126

In [30]:
start_scores=outputs.start_logits
end_scores=outputs.end_logits
start_scores,end_scores

(tensor([[-0.7289,  0.0216, -0.0084, -0.3371, -0.0077,  0.0030,  0.0014, -0.3549,
          -0.2049, -0.2091,  0.2694,  0.1048, -0.1884, -0.0416, -0.4374, -0.3508,
          -0.4671, -0.2463, -0.0794, -0.5153,  0.0374, -0.0657,  0.1103, -0.1523,
          -0.1970, -0.2279, -0.0684,  0.1575, -0.1281, -0.3709, -0.0592, -0.0275,
          -0.2474,  0.1341, -0.1313, -0.3445, -0.4873,  0.2079,  0.0503, -0.4922,
          -0.4787, -0.2708,  0.1646, -0.5863,  0.0662, -0.1516, -0.4108, -0.2930,
          -0.1739, -0.1531, -0.4577, -0.1034,  0.0865, -0.3849, -0.4483, -0.2298,
          -0.1915, -0.5178, -0.3446, -0.4866, -0.5707, -0.2190, -0.3965, -0.3881,
          -0.3193, -0.0837, -0.5666, -0.3479,  0.1039, -0.1174,  0.1737,  0.1091]]),
 tensor([[-0.1349,  0.1796,  0.2238,  0.1317, -0.0844, -0.5774, -0.0758,  0.5350,
           0.4935,  0.1708,  0.0574, -0.0029, -0.4027,  0.2622, -0.0501,  0.1308,
          -0.1449, -0.1009,  0.3041, -0.1267, -0.0553,  0.1756,  0.1007, -0.0187,
          -0.

In [31]:
start_index=torch.argmax(start_scores)
end_index=torch.argmax(end_scores)
start_index, end_index

(tensor(10), tensor(66))

In [32]:
answer_tokens = input_ids[0][start_index:end_index]
answer_tokens

tensor([15212,   102, 26191,  3749,  1037, 22979,  1998, 12090,  2126,  2000,
         2490,  3452,  2740,  1998,  2092,  1011,  2108,  1012,  6666,  2421,
         4637, 17886,  3512,  2740,  1010,  9229,  2540,  2740,  1010,  1998,
         4346,  2943,  1012,  2027,  1005,  2128,  2036,  1037,  3019,  3120,
         1997, 23210,  1010,  2029,  2064, 13225, 26369,  2015,  2302,  1996,
         2794,  5699,  1998, 29167,  2015,  2179])

In [33]:
answer_text = tokenizer.decode(answer_tokens, skip_special_tokens=True)
answer_text

"banana bananas offer a versatile and delicious way to support overall health and well - being. benefits include supporting digestive health, improving heart health, and providing energy. they're also a natural source of sweetness, which can satisfy cravings without the added sugar and additives found"

In [35]:
from transformers import TrainingArguments, Trainer

In [37]:
from transformers import DefaultDataCollator

In [38]:
dataCollator=DefaultDataCollator()

In [36]:
args=TrainingArguments(
    output_dir="fineTunedBERT",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    weight_decay=0.01
)

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [40]:
def prepare_train_features(examples):
    # Tokenize the questions and contexts (passage) together, truncating the context if it's too long
    # Padding will be done later, dynamically, when batching examples together
    tokenized_examples = tokenizer(
        examples["question"],
        examples["context"],
        truncation="only_second",  # Truncate context, not the question
        max_length=384,            # Maximum length of the combined input
        stride=128,                # Stride size for sliding window
        return_overflowing_tokens=True,  # Handle long contexts
        return_offsets_mapping=True,     # Get the character-to-token mapping
        padding="max_length"             # Pad all samples to max_length
    )

    # Map from an input example to its corresponding set of tokenized examples
    sample_mapping = tokenized_examples.pop("overflow_to_sample_mapping")
    offset_mapping = tokenized_examples.pop("offset_mapping")

    # Initialize lists for start and end positions
    tokenized_examples["start_positions"] = []
    tokenized_examples["end_positions"] = []

    # Iterate over each example
    for i, offsets in enumerate(offset_mapping):
        # Find the original example corresponding to this tokenized example
        input_ids = tokenized_examples["input_ids"][i]
        cls_index = input_ids.index(tokenizer.cls_token_id)

        # Get the start and end character positions of the answer
        sample_index = sample_mapping[i]
        answers = examples["answers"][sample_index]
        if len(answers["answer_start"]) == 0:  # If no answer, set CLS index as the answer position
            tokenized_examples["start_positions"].append(cls_index)
            tokenized_examples["end_positions"].append(cls_index)
        else:
            # Find the start and end character positions of the answer in the text
            start_char = answers["answer_start"][0]
            end_char = start_char + len(answers["text"][0])

            # Find the token that corresponds to the start of the answer
            token_start_index = 0
            token_end_index = len(input_ids) - 1

            # Skip tokens that are not part of the context
            sequence_ids = tokenized_examples.sequence_ids(i)
            while sequence_ids[token_start_index] != 1:
                token_start_index += 1
            while sequence_ids[token_end_index] != 1:
                token_end_index -= 1

            # Detect if the answer is out of bounds
            if not (offsets[token_start_index][0] <= start_char and offsets[token_end_index][1] >= end_char):
                tokenized_examples["start_positions"].append(cls_index)
                tokenized_examples["end_positions"].append(cls_index)
            else:
                # Otherwise, set the start and end token indices for the answer
                while token_start_index < len(offsets) and offsets[token_start_index][0] <= start_char:
                    token_start_index += 1
                while token_end_index > 0 and offsets[token_end_index][1] >= end_char:
                    token_end_index -= 1

                tokenized_examples["start_positions"].append(token_start_index - 1)
                tokenized_examples["end_positions"].append(token_end_index + 1)

    return tokenized_examples


In [43]:
example=squad["validation"][:1]
example

{'id': ['56be4db0acb8001400a502ec'],
 'title': ['Super_Bowl_50'],
 'context': ['Super Bowl 50 was an American football game to determine the champion of the National Football League (NFL) for the 2015 season. The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl title. The game was played on February 7, 2016, at Levi\'s Stadium in the San Francisco Bay Area at Santa Clara, California. As this was the 50th Super Bowl, the league emphasized the "golden anniversary" with various gold-themed initiatives, as well as temporarily suspending the tradition of naming each Super Bowl game with Roman numerals (under which the game would have been known as "Super Bowl L"), so that the logo could prominently feature the Arabic numerals 50.'],
 'question': ['Which NFL team represented the AFC at Super Bowl 50?'],
 'answers': [{'text': ['Denver Broncos', 'Denver Broncos', 'Denver Br

In [44]:
prepare_train_features(example)

{'input_ids': [[101, 2029, 5088, 2136, 3421, 1996, 10511, 2012, 3565, 4605, 2753, 1029, 102, 3565, 4605, 2753, 2001, 2019, 2137, 2374, 2208, 2000, 5646, 1996, 3410, 1997, 1996, 2120, 2374, 2223, 1006, 5088, 1007, 2005, 1996, 2325, 2161, 1012, 1996, 2137, 2374, 3034, 1006, 10511, 1007, 3410, 7573, 14169, 3249, 1996, 2120, 2374, 3034, 1006, 22309, 1007, 3410, 3792, 12915, 2484, 1516, 2184, 2000, 7796, 2037, 2353, 3565, 4605, 2516, 1012, 1996, 2208, 2001, 2209, 2006, 2337, 1021, 1010, 2355, 1010, 2012, 11902, 1005, 1055, 3346, 1999, 1996, 2624, 3799, 3016, 2181, 2012, 4203, 10254, 1010, 2662, 1012, 2004, 2023, 2001, 1996, 12951, 3565, 4605, 1010, 1996, 2223, 13155, 1996, 1000, 3585, 5315, 1000, 2007, 2536, 2751, 1011, 11773, 11107, 1010, 2004, 2092, 2004, 8184, 28324, 2075, 1996, 4535, 1997, 10324, 2169, 3565, 4605, 2208, 2007, 3142, 16371, 28990, 2015, 1006, 2104, 2029, 1996, 2208, 2052, 2031, 2042, 2124, 2004, 1000, 3565, 4605, 1048, 1000, 1007, 1010, 2061, 2008, 1996, 8154, 2071, 14500

In [46]:
tokenized_dataset=squad.map(prepare_train_features, batched=True, remove_columns=squad["train"].column_names)

Map:   0%|          | 0/87599 [00:00<?, ? examples/s]

Map:   0%|          | 0/10570 [00:00<?, ? examples/s]

In [48]:
tokenized_dataset["train"],tokenized_dataset["validation"]

(Dataset({
     features: ['input_ids', 'token_type_ids', 'attention_mask', 'start_positions', 'end_positions'],
     num_rows: 88524
 }),
 Dataset({
     features: ['input_ids', 'token_type_ids', 'attention_mask', 'start_positions', 'end_positions'],
     num_rows: 10784
 }))

In [52]:
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized_dataset["train"].select(range(1000)),
    eval_dataset=tokenized_dataset["validation"].select(range(1000)),
    tokenizer=tokenizer,
    data_collator=dataCollator
)
trainer.train()

TrainOutput(global_step=125, training_loss=3.7584853515625, metrics={'train_runtime': 108.333, 'train_samples_per_second': 9.231, 'train_steps_per_second': 1.154, 'total_flos': 195972567552000.0, 'train_loss': 3.7584853515625, 'epoch': 1.0})

In [60]:
from transformers import BertTokenizer, BertForQuestionAnswering
import torch
model_path = "/content/fineTunedBERT/checkpoint-125"
model = BertForQuestionAnswering.from_pretrained(model_path)
tokenizer = BertTokenizer.from_pretrained(model_path)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model.to(device)
model.eval()
question = "What is the capital of France?"
context = "France, a country in Western Europe, has Paris as its capital city."

inputs = tokenizer(
    question,
    context,
    return_tensors="pt",
    max_length=384,
    truncation=True,
    padding="max_length"
)


inputs = {key: value.to(device) for key, value in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)

start_logits = outputs.start_logits
end_logits = outputs.end_logits
start_index = torch.argmax(start_logits)
end_index = torch.argmax(end_logits)

answer_tokens = inputs['input_ids'][0][start_index:end_index + 1]
answer = tokenizer.decode(answer_tokens, skip_special_tokens=True)

print(f"Answer: {answer}")


Answer: paris
